# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MST', 'Math, Science, and Technology'), ('SSP', 'Social Sciences and '), ('AH', 'Arts and Humanities')], max_length=50)),
                ('schedule', models.CharField(max_length=20)),
                ('units', models.IntegerField(default='2')),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('sais_number', models.CharField(max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_contact', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=50)),
                ('father_contact', models.CharField(max_length=20)),
                ('year_begin', models.DateField()),
                ('current_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollment.Address')),
                ('home_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollment.Address')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='enrollment.Institution')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='enrollment.Program')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_handled', to='enrollment.Instructor'),
        ),
    ]
