# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollment', '0002_auto_20160529_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='institution_id',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='program_id',
            new_name='program',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
